# Generated by Django 4.1.6 on 2023-03-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LastRightHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_right_holder_number', models.TextField(blank=True, db_column='LAST_RIGHT_HOLDER_NUMBER', null=True)),
                ('last_right_holder_name', models.TextField(blank=True, db_column='LAST_RIGHT_HOLDER_NAME', null=True)),
                ('last_right_holder_address', models.TextField(blank=True, db_column='LAST_RIGHT_HOLDER_ADDRESS', null=True)),
                ('last_right_holder_country', models.TextField(blank=True, db_column='LAST_RIGHT_HOLDER_COUNTRY', null=True)),
                ('registration_number', models.TextField(blank=True, db_column='REGISTRATION_NUMBER', null=True)),
                ('transfer_date', models.DateTimeField(blank=True, db_column='TRANSFER_DATE', null=True)),
            ],
            options={
                'db_table': 'LAST_RIGHT_HOLDER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.TextField(blank=True, db_column='REGISTRATION_DATE', null=True)),
                ('start_annual', models.TextField(blank=True, db_column='START_ANNUAL', null=True)),
                ('last_annual', models.TextField(blank=True, db_column='LAST_ANNUAL', null=True)),
                ('ent_degree', models.TextField(blank=True, db_column='ENT_DEGREE', null=True)),
                ('payment_fee', models.TextField(blank=True, db_column='PAYMENT_FEE', null=True)),
                ('payment_date', models.TextField(blank=True, db_column='PAYMENT_DATE', null=True)),
                ('registration_number', models.TextField(blank=True, db_column='REGISTRATION_NUMBER', null=True)),
                ('transfer_date', models.DateTimeField(blank=True, db_column='TRANSFER_DATE', null=True)),
            ],
            options={
                'db_table': 'REGISTRATION_FEE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationRightHolderA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_number', models.TextField(blank=True, db_column='RANK_NUMBER', null=True)),
                ('rank_correlator_serial_number', models.TextField(blank=True, db_column='RANK_CORRELATOR_SERIAL_NUMBER', null=True)),
                ('rank_correlator_type', models.TextField(blank=True, db_column='RANK_CORRELATOR_TYPE', null=True)),
                ('rank_correlator_name', models.TextField(blank=True, db_column='RANK_CORRELATOR_NAME', null=True)),
                ('rank_correlator_address', models.TextField(blank=True, db_column='RANK_CORRELATOR_ADDRESS', null=True)),
                ('registration_number', models.TextField(blank=True, db_column='REGISTRATION_NUMBER', null=True)),
                ('transfer_date', models.DateTimeField(blank=True, db_column='TRANSFER_DATE', null=True)),
            ],
            options={
                'db_table': 'REGISTRATION_RIGHT_HOLDER_A',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationRightHolderB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_number', models.CharField(blank=True, db_column='RANK_NUMBER', max_length=10, null=True)),
                ('document_name', models.CharField(blank=True, db_column='DOCUMENT_NAME', max_length=10, null=True)),
                ('receipt_date', models.CharField(blank=True, db_column='RECEIPT_DATE', max_length=10, null=True)),
                ('registration_cause_name', models.CharField(blank=True, db_column='REGISTRATION_CAUSE_NAME', max_length=10, null=True)),
                ('indecation_of_event', models.CharField(blank=True, db_column='INDECATION_OF_EVENT', max_length=10, null=True)),
                ('registration_number', models.CharField(blank=True, db_column='REGISTRATION_NUMBER', max_length=10, null=True)),
                ('transfer_date', models.DateTimeField(blank=True, db_column='TRANSFER_DATE', null=True)),
            ],
            options={
                'db_table': 'REGISTRATION_RIGHT_HOLDER_B',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationRightRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_number', models.TextField(blank=True, db_column='RANK_NUMBER', null=True)),
                ('pertinent_partition', models.TextField(blank=True, db_column='PERTINENT_PARTITION', null=True)),
                ('document_name', models.TextField(blank=True, db_column='DOCUMENT_NAME', null=True)),
                ('original_registration_number', models.TextField(blank=True, db_column='ORIGINAL_REGISTRATION_NUMBER', null=True)),
                ('registration_purpose', models.TextField(blank=True, db_column='REGISTRATION_PURPOSE', null=True)),
                ('registration_date', models.TextField(blank=True, db_column='REGISTRATION_DATE', null=True)),
                ('registration_cause_name', models.TextField(blank=True, db_column='REGISTRATION_CAUSE_NAME', null=True)),
                ('registration_cause_date', models.TextField(blank=True, db_column='REGISTRATION_CAUSE_DATE', null=True)),
                ('receipt_number', models.TextField(blank=True, db_column='RECEIPT_NUMBER', null=True)),
                ('receipt_date', models.TextField(blank=True, db_column='RECEIPT_DATE', null=True)),
                ('disappearance_flag', models.TextField(blank=True, db_column='DISAPPEARANCE_FLAG', null=True)),
                ('disappearance_cause_name', models.TextField(blank=True, db_column='DISAPPEARANCE_CAUSE_NAME', null=True)),
                ('disappearance_date', models.TextField(blank=True, db_column='DISAPPEARANCE_DATE', null=True)),
                ('international_reg_record_date_md', models.TextField(blank=True, db_column='INTERNATIONAL_REG_RECORD_DATE_MD', null=True)),
                ('expiration_date_md', models.TextField(blank=True, db_column='EXPIRATION_DATE_MD', null=True)),
                ('latest_renewal_date_md', models.TextField(blank=True, db_column='LATEST_RENEWAL_DATE_MD', null=True)),
                ('sub_designation_date_md', models.TextField(blank=True, db_column='SUB_DESIGNATION_DATE_MD', null=True)),
                ('registration_number', models.TextField(blank=True, db_column='REGISTRATION_NUMBER', null=True)),
                ('transfer_date', models.DateTimeField(blank=True, db_column='TRANSFER_DATE', null=True)),
            ],
            options={
                'db_table': 'REGISTRATION_RIGHT_RANK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.TextField(blank=True, db_column='REGISTRATION_NUMBER', null=True)),
                ('registration', models.TextField(blank=True, db_column='REGISTRATION', null=True)),
            ],
            options={
                'db_table': 'REG_UPDATE_HISTORY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RightHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertinent_partition', models.CharField(blank=True, db_column='PERTINENT_PARTITION', max_length=10, null=True)),
                ('rank_number', models.CharField(blank=True, db_column='RANK_NUMBER', max_length=10, null=True)),
                ('registration_date', models.CharField(blank=True, db_column='REGISTRATION_DATE', max_length=10, null=True)),
                ('rank_correlator_serial_number', models.CharField(blank=True, db_column='RANK_CORRELATOR_SERIAL_NUMBER', max_length=10, null=True)),
                ('rank_correlator_number', models.CharField(blank=True, db_column='RANK_CORRELATOR_NUMBER', max_length=100, null=True)),
                ('rank_correlator_type', models.CharField(blank=True, db_column='RANK_CORRELATOR_TYPE', max_length=100, null=True)),
                ('rank_correlator_name', models.CharField(blank=True, db_column='RANK_CORRELATOR_NAME', max_length=100, null=True)),
                ('rank_correlator_address', models.CharField(blank=True, db_column='RANK_CORRELATOR_ADDRESS', max_length=100, null=True)),
                ('transfer_date', models.DateTimeField(blank=True, db_column='TRANSFER_DATE', null=True)),
                ('registration_number', models.CharField(blank=True, db_column='REGISTRATION_NUMBER', max_length=10, null=True)),
            ],
            options={
                'db_table': 'RIGHT_HOLDER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RightholderbQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_number', models.CharField(blank=True, db_column='RANK_NUMBER', max_length=2, null=True)),
                ('document_name', models.CharField(blank=True, db_column='DOCUMENT_NAME', max_length=10, null=True)),
                ('receipt_date', models.CharField(blank=True, db_column='RECEIPT_DATE', max_length=10, null=True)),
                ('registration_cause_name', models.CharField(blank=True, db_column='REGISTRATION_CAUSE_NAME', max_length=10, null=True)),
                ('indecation_of_event', models.CharField(blank=True, db_column='INDECATION_OF_EVENT', max_length=10, null=True)),
                ('registration_number', models.CharField(blank=True, db_column='REGISTRATION_NUMBER', max_length=20, null=True)),
                ('transfer_date', models.DateTimeField(blank=True, db_column='TRANSFER_DATE', null=True)),
            ],
            options={
                'db_table': 'rightHolderB_query',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KipoAdminRegBs',
            fields=[
                ('registernumber', models.TextField(blank=True, db_column='registerNumber', null=True)),
                ('registerationdate', models.TextField(blank=True, db_column='registerationDate', null=True)),
                ('examinationdate', models.TextField(blank=True, db_column='examinationDate', null=True)),
                ('existduringdate', models.TextField(blank=True, db_column='existDuringDate', null=True)),
                ('lapscause', models.TextField(blank=True, db_column='lapsCause', null=True)),
                ('lapsdate', models.TextField(blank=True, db_column='lapsDate', null=True)),
                ('applicationnumber', models.TextField(blank=True, db_column='applicationNumber', null=True)),
                ('applicationdate', models.TextField(blank=True, db_column='applicationDate', null=True)),
                ('publicationnumber', models.TextField(blank=True, db_column='publicationNumber', null=True)),
                ('publicationdate', models.TextField(blank=True, db_column='publicationDate', null=True)),
                ('internationregistrationnumber', models.TextField(blank=True, db_column='internationRegistrationNumber', null=True)),
                ('internationregistrationdate', models.TextField(blank=True, db_column='internationRegistrationDate', null=True)),
                ('originalapplicationnumber', models.TextField(blank=True, db_column='originalApplicationNumber', null=True)),
                ('originalapplicationdate', models.TextField(blank=True, db_column='originalApplicationDate', null=True)),
                ('classificationcode', models.TextField(blank=True, db_column='classificationCode', null=True)),
                ('inventiontitle', models.TextField(blank=True, db_column='inventionTitle', null=True)),
                ('inventiontitleeng', models.TextField(blank=True, db_column='inventionTitleEng', null=True)),
                ('claimcount', models.TextField(blank=True, db_column='claimCount', null=True)),
                ('prioritycountry', models.TextField(blank=True, db_column='priorityCountry', null=True)),
                ('prioritydate', models.TextField(blank=True, db_column='priorityDate', null=True)),
                ('prioritycount', models.TextField(blank=True, db_column='priorityCount', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'KIPO_ADMIN_REG_BS',
            },
        ),
    ]
